[versions]
kotest = "6.0.0.M1"
kafka = "3.9.0"
kotlin = "2.1.0"
kotlinx-coroutines = "1.10.1"
dokka = "2.0.0"
knit = "0.5.0"
kover = "0.9.1"
testcontainers-kafka = "1.20.4"
slf4j = "2.0.16"
spotless = "7.0.2"
publish = "0.30.0"

[libraries]
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kafka-connect = { module = "org.apache.kafka:connect-runtime", version.ref = "kafka" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
kafka-streams = { module = "org.apache.kafka:kafka-streams", version.ref = "kafka" }
kotlin-scripting-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers-kafka" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
knit = { id = "org.jetbrains.kotlinx.knit", version.ref = "knit" }
